language: generic
os: osx

# https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version
matrix:
  include:
    - osx_image: xcode8.3 # macOS Sierra v10.12
    - osx_image: xcode7.3 # OS X El Capitan v10.11
    - osx_image: xcode6.4 # OS X Yosemite v10.10

before_install:
  # Download and install a minimal TeX Live, based on
  # https://github.com/latex3/latex3/blob/master/support/texlive.sh.
  - wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  - tar -xzf install-tl-unx.tar.gz
  - cd install-tl-20*
  - echo -e "selected_scheme scheme-minimal\nTEXDIR /usr/local/texlive\noption_doc 0\noption_src 0" > texlive.profile
  - sudo ./install-tl -profile=texlive.profile
  - cd ..
  - PATH=$PATH:/usr/local/texlive/bin/x86_64-darwin
  - sudo tlmgr install
    datetime2
    datetime2-english
    ec
    etoolbox
    fancyhdr
    fontspec
    geometry
    graphics
    hyperref
    lastpage
    libertine
    lm
    oberdiek
    pgf
    soul
    standalone
    tracklang
    url
    varwidth
    xcolor
    xetex
    xkeyval
    zapfding
  - ln -s /usr/local/texlive/texmf-dist/fonts/opentype/public/libertine ~/Library/Fonts/libertine

  # The Travis CI OS X Yosemite v10.10 image lacks pip.
  - pip install requests || sudo easy_install requests

script:
  - python --version
  - python init.py
  - python make_leases.py
